### ISSUE TITLE
Version 1.1.0 doesn't do anything

### ISSUE THREAD

**Issue by pannal** [inoahguy02/maxwell-cutoff-fix#15]
`-showall` doesn't print anything, in fact the whole thing doesn't print anything:
![image](https://github.com/inoahguy02/maxwell-cutoff-fix/assets/1359593/284922a7-6ef4-4d93-9cfb-d2c9ab82f237)

Also I think your release notes are wrong - the source code mentions `--showall`, not `-showall`. But that didn't print anything for me, either.

**Comment by inoahguy02** [comment]
Ah, went over my head. I made a change where it won't display a terminal on a release build. I'll add this fix in v1.1.1

I went ahead and fixed the typo in the release notes

**Comment by inoahguy02** [comment]
Fixed in v1.1.1
