### ISSUE TITLE
Dev version

### ISSUE THREAD

**Issue by pannal** [inoahguy02/maxwell-cutoff-fix#20]
Hey, I've just built the project from the current master tree, is this expected behaviour?

![image](https://github.com/inoahguy02/maxwell-cutoff-fix/assets/1359593/479926ae-43f0-4d96-b872-77f9f0f44b3f)
(the repetition)

Also, is it expected to open a console when invoked without CLI?

**Comment by inoahguy02** [comment]
Yeah that's intended for the debug build only. If you build it using `cargo build`, it will build the debug one

`cargo build --release` will make an executable in `/target/release`. This is the one that should be ran if you do not want the window to pop up

**Comment by inoahguy02** [comment]
I had a condition for the window close function that made it to where it only ran if the built OS was Windows, but the condition somehow didn't work. This should be fixed now
