### ISSUE TITLE
On restart, folder holding log files always opens

### ISSUE THREAD

**Issue by shanep2300** [inoahguy02/maxwell-cutoff-fix#21]
In startup folder I have maxwell-cutoff-fix.exe and the folder.

![image](https://github.com/inoahguy02/maxwell-cutoff-fix/assets/16820289/3863e07d-bc40-4856-838e-71e888106edf)

**Comment by inoahguy02** [comment]
I made it so that the program can now be placed anywhere on the system and will still auto run on start up as long as it has run at least once in the directory. This will be added in next release
